
spring.datasource.url=jdbc:postgresql://dpg-d8sie3e7r5hc73fi7bo0-a:5432/yogurt_db_cr6d
spring.datasource.username=yogurt_db_cr6d_user
spring.datasource.password=2FLxj70akVeqQAfeEiIqx59YF4zusDIl
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true